### ISSUE TITLE
  reRichtext.fromHtml() 图片无法加载

### ISSUE THREAD

**Issue by honganxue** [sophimp/android-richtext-editor#1]
使用reRichtext.fromHtml()  加载富文本时,无法显示图片!

**Comment by sophimp** [comment]
> 使用reRichtext.fromHtml() 加载富文本时,无法显示图片!

发html 看一看，是网络图片，还是本地图片不能加载

如果是本地选择的图片，要多端同步，这部分的工作需要自己做， 将上传的html里的本地路径换成网络路径
