### ISSUE TITLE
选中段落缩进，缩进一次后就自动取消选中了，这个可以修复一下吗

### ISSUE THREAD

**Issue by jack9095** [sophimp/android-richtext-editor#6]
选中段落缩进，缩进一次后就自动取消选中了，这个可以修复一下吗

**Comment by sophimp** [comment]
已经修了，拉下代码

**Comment by jack9095** [comment]
> 已经修了，拉下代码

还有这个问题哦，没修复呢，麻烦再看一下噶

**Comment by sophimp** [comment]
可以了，上次只修了选中一段的情况

**Comment by jack9095** [comment]
> > 已经修了，拉下代码
> 
> 还有这个问题哦，没修复呢，麻烦再看一下噶

可以了，方便加个微信吗，顺便请你喝杯咖啡，感谢您的付出

**Comment by sophimp** [comment]
微信号：sophimp 
交个朋友，咖啡就不必啦。
